### ISSUE TITLE
Mollie Test naar Live

### ISSUE THREAD

**Issue by ernstwys** [mollie/mollie-api-ruby#119]
Ben bezig geweest met een developer om de recurring functie te configureren in Rails.
Na het overstappen van de Test api naar Live, krijg ik  deze melding.

Mollie::RequestError (404 Not Found: Customer cst_UKAmzEESQv exists, but the wrong mode is used. Try switching live / test API keys.):

Enig idee?

**Comment by vernondegoede** [comment]
Did you create the customer using the same API key?

**Comment by ernstwys** [comment]
Most of the users were existing, yes

**Comment by vernondegoede** [comment]
Customers can also be created in test mode (which will happen when using the test API key), which means that you can only create live recurring payments using customers that were also created in live mode.

Let me know if you run into any additional issues 👍

**Comment by ernstwys** [comment]
That was it... Thanks for the quick response

**Comment by lucasdegen** [comment]
Thank you so much, I'm using wobbie form on my WordPress website.
But I forgot to change the live mollie API in the form setting, so under test mode a order was placed.
I could not see the order details, because I added the live API key later.

So thanks to your solution, I temporary switched back to test modes and I could see the adress of the order.
And set back to live modes.
