### ISSUE TITLE
NoMethodError when calling getPaymentUrl.

### ISSUE THREAD

**Issue by jurriaan** [mollie/mollie-api-ruby#4]
I don't exactly know what happened here, but I think my code tried to request a payment URL from a closed payment. 

```
(undefined method `paymentUrl' for #<Mollie::API::Object::Base:0x007f4c2c1c4498>):
  mollie-api-ruby (1.1.1) lib/Mollie/API/Object/Payment.rb:34:in `getPaymentUrl'
```

**Comment by dhiemstra** [comment]
:+1: it seems the API doesn't return a paymentUrl inside the links hash when requesting a existing payment.

**Comment by Daanvm** [comment]
Hi Juriaan and Danny,
Thanks for bringing this to our attention and apologies for the late reply!

Is this issue still relevant?

**Comment by dhiemstra** [comment]
Yes @Daanvm 

I just tested it with the latest version of the gem and this is still an issue.

```
>> payment = api.payments.get('tr_hgmsC2apvN')
=> #<Mollie::API::Object::Payment:0x007fa86a1336d8...>
>> payment.getPaymentUrl
NoMethodError: undefined method `paymentUrl' for #<Mollie::API::Object::Base:0x007fa86a1325d0>
```

The problem lies in [/lib/Mollie/API/Object/Payment.rb#L61](https://github.com/mollie/mollie-api-ruby/blob/master/lib/Mollie/API/Object/Payment.rb#L61) which expects the API to return a `paymentUrl` entry inside the JSON `links` block.
If you'd return this `paymentUrl` in your `GET /payments` API that would fix this issue.

We offer our customers a Mollie integration and handle almost 2000 mollie payments a month.
Thankfully this is only an issue when a client somehow comes back to our page which redirects them to mollie (for example using the back button). Ideally we'd like to fetch the payment to see if it's still valid and then redirect the user to the `paymentUrl` again. This is not a major issue but it's a very annoying one.

Hopefully you can fix this soon.

**Comment by Daanvm** [comment]
Our api does return the paymentUrl for open payments. When a payment has a final state we don't return the paymentUrl anymore, because there is nothing to do for the consumer. However, this shouldn't result in an error in our client.

I'm not a ruby developer myself, so we have to wait a few weeks before our ruby developer is coming back from vacation. When someone is willing to create a PR I would be happy to review and merge it though.

**Comment by dhiemstra** [comment]
Hi @Daanvm,

I've debugged this and you're right.
I think we somehow sometimes try to get the paymentUrl while the state is not `open`.
We should check the `state` here on our side anyway so for us this issue is not relevant anymore.

Thanks for your explanation.

**Comment by Daanvm** [comment]
Good to head that @dhiemstra

**Comment by benoist** [comment]
In 2.0.0 it returns nil instead of raising errors, you could probably add milestone 2.0.0 and close this

**Comment by Daanvm** [comment]
It will only be a small fix, so I'll fix this also for the current release.

**Comment by Daanvm** [comment]
It's 6 months later and I can't remember why we should fix this in an old version of our api. This is fixed in the latest version of our client. Using the latest version is always a good idea :)
